services:
  frps:
    image: snowdreamtech/frps:0.71.0-debian
    restart: unless-stopped

    command:
      - "-c"
      - "/etc/frp/frps.toml"

    environment:
      FRP_TOKEN: ${FRP_TOKEN}

    volumes:
      - ./frps.toml:/etc/frp/frps.toml:ro

    expose:
      - "7000"
      - "8080"

    networks:
      - dokploy-network

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=dokploy-network"

      # ============================================================
      # 1. FRPC -> FRPS
      #
      # https://tunnel.gedeon.care/~!frp
      #              ↓
      #         Traefik TLS
      #              ↓
      #         frps:7000
      # ============================================================

      - "traefik.http.routers.gedeon-frps-control.rule=Host(`tunnel.gedeon.care`) && Path(`/~!frp`)"
      - "traefik.http.routers.gedeon-frps-control.entrypoints=websecure"
      - "traefik.http.routers.gedeon-frps-control.tls=true"
      - "traefik.http.routers.gedeon-frps-control.tls.certresolver=letsencrypt"
      - "traefik.http.routers.gedeon-frps-control.service=gedeon-frps-control"
      - "traefik.http.routers.gedeon-frps-control.priority=2000"

      - "traefik.http.services.gedeon-frps-control.loadbalancer.server.port=7000"
      - "traefik.http.services.gedeon-frps-control.loadbalancer.server.scheme=http"


      # ============================================================
      # 2. HTTP public des tunnels
      #
      # https://api-pierre.fprs.gedeon.care
      # https://s3-pierre.fprs.gedeon.care
      #              ↓
      #         Traefik TLS
      #              ↓
      #         frps:8080
      #              ↓
      #            FRP
      # ============================================================

      - 'traefik.http.routers.gedeon-frps-public.rule=HostRegexp(`^.+[.]fprs[.]gedeon[.]care$`)'
      - "traefik.http.routers.gedeon-frps-public.entrypoints=websecure"
      - "traefik.http.routers.gedeon-frps-public.tls=true"
      - "traefik.http.routers.gedeon-frps-public.service=gedeon-frps-public"
      - "traefik.http.routers.gedeon-frps-public.priority=1000"

      - "traefik.http.services.gedeon-frps-public.loadbalancer.server.port=8080"
      - "traefik.http.services.gedeon-frps-public.loadbalancer.server.scheme=http"
      - "traefik.http.services.gedeon-frps-public.loadbalancer.passhostheader=true"


networks:
  dokploy-network:
    external: true